import { Poppins } from 'next/font/google';
import "./globals.css";
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';

const poppins = Poppins({
  subsets: ['latin'], // Use Latin subset
  weight: ['400', '600', '700'], // You can add any specific weights you want to use
  style: ['normal', 'italic'], // Optionally load italic styles
})


export const metadata = {
  title: "SkillsGro",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} bg-gray-100 antialiased`}
      >
        <Navbar/>
      
        {children}
        <Footer/>
      </body>
    </html>
  );
}
